theme: jekyll-theme-cayman
title: Reproduction project CRFNet
description: This website describes how the CRFNet repository can be reproduced.

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Prepare System
      url: /preparesystem/
      weight: 2

    - name: Configure and Use
      url: /confuse/
      weight: 3

    - name: Troubleshooting
      url: /troubleshooting/
      weight: 4

    - name: Conclusion
      url: /conclusion/
      weight: 5